apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.service.name }}-alb
  namespace: {{ .Values.namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internal # Private ALB
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]' # Specify listener ports
    alb.ingress.kubernetes.io/target-type: ip # Targets pods directly
    alb.ingress.kubernetes.io/backend-protocol: HTTP # Protocol used by service
    alb.ingress.kubernetes.io/load-balancer-attributes: |
      idle_timeout.timeout_seconds=60
    alb.ingress.kubernetes.io/subnets: "subnet-07fc9d0778cc24b34,subnet-0066b10eba41f1c33" # Private subnets
spec:
  rules:
  {{- if .Values.ingress.host }}
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.port }}
  {{- else }}
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.port }}
  {{- end }}
